ecommerce/apps/session/urls.py
from django.urls import path
from . import views

app_name = 'session'

urlpatterns = [
    path('', views.basket_home, name="basket"),
    path('add/', views.add, name="add"),
    path('update/', views.update, name="update"),
    path('delete', views.delete, name="delete"),

]

ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/', include('ecommerce.apps.offert_api.urls', namespace='blog_api')),
    path("dashboard/", include("ecommerce.apps.charts.urls", namespace="charts")),
    path("basket/", include("ecommerce.apps.session.urls", namespace="session")),
    path("", include("ecommerce.apps.offert.urls", namespace="offert")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ecommerce/apps/session/views.py
from django.shortcuts import get_object_or_404, render
from .session import Session
from django.http import JsonResponse
from ecommerce.apps.offert.models import Product
import numpy as np


def basket_home(request):
    # width = request.GET.get('width')
    session = Session(request)
    total_price = session.get_total_price()
    product_ids = [i for i in session.current_session.keys()]
    products = Product.objects.filter(id__in=product_ids)

    for product in products:
        session.current_session[str(product.id)]['product'] = product

    context = {
        'session': session,
        'total_price': total_price,
        # 'width': width,
    }
    return render(request, "session/basket_home.html", context)


def add(request):
    session = Session(request)
    if request.method == 'POST':
        qty = request.POST.get('qty')
        product_id = request.POST.get('product_id')
        session.add(get_object_or_404(Product, id=product_id), qty=qty)

        context = {'qty': qty,
                   'product_id': product_id,
                   'basket_qty': session.total_items_number(),
                   }
        return JsonResponse(context)


def update(request):
    session = Session(request)
    if request.method == 'POST':
        pk = request.POST.get('pk')
        id_type = request.POST.get('id_type')
        qty = request.POST.get('qty')
        qty = int(qty)
        product = get_object_or_404(Product, id=int(pk))
        product_qty_store = product.quantity
        limit = False
        if id_type == 'add-item':
            if int(qty) + 1 <= int(product_qty_store):
                qty += 1
                session.add(product, qty)
            else:
                limit = True
        if id_type == 'remove-item':
            if int(qty) - 1 > 0:
                qty -= 1
                session.add(product, qty)
    context = {
        'pk': pk,
        'id_type': id_type,
        'qty': qty,
        'price': np.round(session.current_session[pk]['subtotal_price'], 2),
        'total_price': session.get_total_price(),
        'basket_qty': session.total_items_number(),
        'limit': limit,

    }
    print(context)
    return JsonResponse(context)


def delete(request):
    session = Session(request)
    if request.method == "POST":
        pk = request.POST.get('pk')
        session.delete(pk)

    context = {
        'session': session.current_session,
        'total_price': session.get_total_price(),
        'basket_qty': session.total_items_number(),
    }
    return JsonResponse(context)

templates/session/basket_home.html
{% extends "base.html" %}
{% load static %}
{% load custom_template_tags %}
{% block title %}Basket{% endblock %}
{% block stylesheet %}{% static "session/css/session.css" %}{% endblock %}
{% block content %}
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Order Confirmation</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Are you sure you want to continue?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-success">Confirm</button>
        </div>
        </div>
    </div>
    </div>
    <div id="liveAlertPlaceholder"></div> 
    <div class="row">
        {% for s in session.current_session.values %}
        <div class="card border mt-3 product-card" data-index="{{s.product.pk}}">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-sm-6 col-md-2 ps-0 pe-0">
                        <div class="card">
                            <div class="card-header card-header-start text-center d-none d-lg-block" style="height: 42px;">
                                <span class="fs-6 fw-bold">Image</span>
                            </div>
                            <div class="card-body text-center">
                                {% for p in s.product.product_image.all %}
                                    {% if p.default == True %}
                                        <img src="{{p.image.url}}" width="100px" height="100px" alt="">
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3 ps-0 pe-0">
                        <div class="card">
                            <div class="card-header card-header-middle text-center d-none d-lg-block" style="height: 42px;">
                                <span class="fs-6 fw-bold">Product name</span>
                            </div>
                            <div class="card-body text-center d-flex align-items-center justify-content-center" style="height: 132px;">
                               <span class="fs-5">{{s.product.name}}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-1 ps-0 pe-0">
                        <div class="card">
                            <div class="card-header card-header-middle text-center d-none d-lg-block" style="height: 42px;">
                                <span class="fs-6 fw-bold">Price</span>
                            </div>
                            <div class="card-body text-center d-flex align-items-center justify-content-center" style="height: 132px;">
                                <span class="fs-5 fw-bold" id="price{{s.product.pk}}">{{s.subtotal_price}}$</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-4 ps-0 pe-0">
                        <div class="card">
                            <div class="card-header card-header-middle text-center d-none d-lg-block" style="height: 42px;">
                                <span class="fs-6 fw-bold">Qty</span>
                            </div>
                            <div class="card-body text-center d-flex align-items-center justify-content-center" style="height: 132px;">
                                <div class="card border">
                                    <div class="card-body p-0">
                                        <div class="d-flex flex-row">
                                            <span class="ps-3 pe-3 fs-4 d-flex align-items-center border-end" id="quantity{{s.product.pk}}">{{s.qty}}</span>
                                            <div class="d-flex flex-column">
                                                <button class="border-0 ps-0 pe-0" style="background-color:#fff">                                  
                                                <svg class="border-bottom" xmlns="http://www.w3.org/2000/svg" height="28px" viewBox="0 0 24 24" width="28px"
                                                    fill="#000000" data-index="{{s.product.pk}}" id="add-item">
                                                    <path d="M0 0h24v24H0V0z" fill="none" />
                                                    <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
                                                </svg> 
                                                </button>
                                                <button class="border-0 ps-0 pe-0" style="background-color:#fff">                                                                     
                                                <svg xmlns="http://www.w3.org/2000/svg" height="28px" viewBox="0 0 24 24" width="28px"
                                                fill="#000000" data-index="{{s.product.pk}}" id="remove-item">
                                                    <path d="M0 0h24v24H0V0z" fill="none" />
                                                    <path d="M19 13H5v-2h14v2z" />
                                                </svg>
                                                </button>                                      
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-2 ps-0 pe-0">
                        <div class="card">
                            <div class="card-header card-header-middle text-center d-none d-lg-block" style="height: 42px;">
                            </div>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="button" data-index="{{s.product.pk}}"  class="mt-5 ms-3 me-3 btn btn-danger delete-item">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row d-flex justify-content-end ">
        <div class="col-12 col-sm-6 col-md-4 col-lg-3  pe-0">
            <div class="card border mt-3">
                <div class="card-body">
                    <div class="d-flex flex-row">
                        <span class="fs-4">Total price:</span>
                        <span class="ms-1 fs-4 fw-bold" id="basket-summary">{{session.get_total_price}}$</span>
                    </div>
                </div>
            </div>
            <div class="mt-2 d-grid">
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">Confirm an order</button>
            </div>
        </div>
    </div>
</div>
<script>

{% comment %} document.onreadystatechange = function() {
    if (document.readyState !== "complete") {
        var width = screen.width;
        $.ajax({
            type: "GET",
            url: '{% url "session:basket" %}',
            data:{
                width: width,
            }
        })
    } 
}; {% endcomment %}

//Get screen width

//Update
$('#add-item,#remove-item').click(function(e){
    e.preventDefault()
    var pk = $(this).data("index");
    var id_type = $(this).attr('id');
    var qty = $('#quantity'+pk).text()
    var alertPlaceholder = document.getElementById('liveAlertPlaceholder')
    var alertTrigger = document.getElementById('add-item')

    function alert(message, type) {
    var wrapper = document.createElement('div')
    wrapper.innerHTML = '<div class="alert alert-' + type + ' alert-dismissible" role="alert">' +
        message + '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>'

    alertPlaceholder.append(wrapper)
    }

    $.ajax({
        type:"POST",
        url:'{% url "session:update" %}',
        data: {
            pk: pk,
            id_type: id_type,
            qty: qty,
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post',
        },
        success: function(json){
            document.getElementById("quantity"+pk).innerHTML = json.qty;
            document.getElementById("price"+pk).innerHTML = json.price+'$';
            document.getElementById("basket-summary").innerHTML = json.total_price+'$';
            document.getElementById("total-items").innerHTML = json.basket_qty;
            if (json.limit){
                alert('You can not add more items because of store limitations!', 'danger')
            }
        },
        error: function(error){
            console.log(error)
        },
    })
});

//Delete
$('.delete-item').click(function(e){
    var pk = $(this).data("index");

    $.ajax({
        type:"POST",
        url: '{% url "session:delete" %}',
        data: {
            pk:pk,
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post',
        },
        success: function(json){
            $('.product-card[data-index="' + pk + '"]').remove();
            document.getElementById("basket-summary").innerHTML = json.total_price+'$';
            document.getElementById("total-items").innerHTML = json.basket_qty;

        },
        error: function(error){
            console.log(error)
        }
    })
});
</script>  

{% endblock %}